const http = require('http');

const data = JSON.stringify({
  email: 'admin@prizmabrixx.com',
  password: 'admin'
});

const req = http.request({
  hostname: 'localhost',
  port: 8080,
  path: '/api/auth/login',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': data.length
  }
}, (res) => {
  let body = '';
  res.on('data', chunk => body += chunk);
  res.on('end', () => {
    const token = JSON.parse(body).token;
    console.log("Token received.");
    
    const leadData = JSON.stringify({
      clientCompany: 'Test AI Client',
      contactName: 'AI Agent',
      phone: '1234567890',
      email: 'ai@agent.com',
      projectName: 'Awesome AI Project',
      description: 'This is a test description generated by AI.',
      referenceLinks: 'https://github.com',
      documentUrl: 'https://docs.google.com'
    });

    const leadReq = http.request({
      hostname: 'localhost',
      port: 8080,
      path: '/api/leads',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
        'Content-Length': leadData.length
      }
    }, (leadRes) => {
      let leadBody = '';
      leadRes.on('data', chunk => leadBody += chunk);
      leadRes.on('end', () => {
        console.log("Lead created:", leadBody);
      });
    });
    
    leadReq.write(leadData);
    leadReq.end();
  });
});

req.write(data);
req.end();
