CREATE TABLE hr_leads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    department_id BIGINT,
    position VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'ONBOARDING', -- ONBOARDING, OFFBOARDING, COMPLETED, REJECTED
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE hr_documents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hr_lead_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_type VARCHAR(50) NOT NULL, -- ONBOARDING, OFFBOARDING
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, UPLOADED, APPROVED
    file_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (hr_lead_id) REFERENCES hr_leads(id) ON DELETE CASCADE
);
